spring:
    datasource:
        url: jdbc:mysql://localhost:3306/task-manager?autoReconnect=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        pool.max-idle: 8
        pool.min-idle: 0
        pool.max-active: 8
        pool.max-wait: -1
        timeout: 5000
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka/
swagger2:
    enable: true